- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False
  tasks:
    - name: Include packages
      include_tasks: tasks/packages.yml
    - debug:
        msg: do I get here?

- name: Include Zsh setup
  import_playbook: zsl.yml
