- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - name: Include Zsh setup
      import_playbook: zsl.yml
