- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False
  tasks:
    - name: Include packages
      include_tasks: tasks/packages.yml

- name: Include Zsh setup
  import_playbook: tasks/zsh.yml
- name: Install Neovim
  import_playbook: tasks/nvim.yml
# - name: Install Docker
#   import_playbook: tasks/docker.yml
- name: Install Dev stuff
  import_playbook: tasks/dev_stuff.yml
