- name: Install Docker
  hosts: localhost
  become: yes
  vars:
      user: stijn
  tasks:
    - name: change user shell to zsh 
      become: yes
      user:
        name: "{{ user }}"
        shell: /bin/zsh
    - name: NVM directory check
      stat:
        path: "/home/{{ user }}/.nvm"
      register: nvm_dir
      become: yes
      become_user: "{{ user }}"
    - name: Install Node Version Manager
      become_user: "{{ user }}"
      when: not nvm_dir.stat.exists
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash 
      args:
        executable: /bin/zsh
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
    - name: Install Node
      become: yes
      become_user: "{{ user }}"
      when: not nvm_dir.stat.exists
      shell: |
        source /home/{{ user }}/.zshrc && nvm install node
      args:
        executable: /bin/zsh

    - name: Ensure keyring directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download and install GitHub CLI keyring
      ansible.builtin.shell: |
        wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
        && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg
      args:
        creates: /etc/apt/keyrings/githubcli-archive-keyring.gpg

    - name: Add GitHub CLI repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
        filename: github-cli

    - name: Update APT package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install GitHub CLI
      ansible.builtin.apt:
        name: gh
        state: present

