- name: Dotfiles and stuff
  hosts: localhost
  become: yes
  vars:
      user: stijn
      nvim_repo: https://github.com/stijnVanHorenbeek/kickstart-modular.nvim.git
  tasks:
    - name: Clone nvim dotfiles
      git:
        repo: {{ nvim_repo }}
        dest: "/home/{{ user }}/.config/nvim"
        version: "main"
        force: yes
      become: yes
      become_user: "{{ user }}"

