- name: Dotfiles and stuff
  hosts: localhost
  become: yes
  vars:
    user: stijn
    nvim_repo: https://github.com/stijnVanHorenbeek/kickstart-modular.nvim.git
    tpm_repo: https://github.com/tmux-plugins/tpm
    tmux_dot_repo: https://github.com/stijnVanHorenbeek/tmux_dotfiles.git

  tasks:
    - name: Clone nvim dotfiles
      git:
        repo: "{{ nvim_repo }}"
        dest: "/home/{{ user }}/.config/nvim"
        version: "master"
        force: yes
      become: yes
      become_user: "{{ user }}"
    - name: Clone tmux plugin manager
      git:
        repo: "{{ tpm_repo }}"
        dest: "/home/{{ user }}/.tmux/plugins/tpm"
        version: "master"
        force: yes
      become: yes
      become_user: "{{ user }}"
    - name: Clone tmux dotfile
      git:
        repo: "{{ tmux_dot_repo }}"
        dest: "/home/{{ user }}/.config/tmux"
        version: "master"
        force: yes
      become: yes
      become_user: "{{ user }}"
