- name: Install packages
  apt:
    name:
      - neofetch
      - htop
      - tmux
      - mc
      - build-essential
      - dotnet-sdk-8.0
      - aspnetcore-runtime-8
      - ripgrep
      - fzf
      - xclip

