- name: Install and configure Zsh and Oh My Zsh
  hosts: localhost
  become: yes
  vars:
      user: stijn
  tasks:
    - name: Ensure Zsh with dependencies are installed
      apt:
        name: zsh
        state: present
      become: true
    - name: Ensure zsh is the default shell
      user:
        name: "{{ ansible_user }}"
        shell: "/usr/bin/zsh"
      become: true
    - name: Download Oh My Zsh installation script
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/install_ohmyzsh.sh

    - name: Changing perm of zsh-install script, adding '+x'
      file: 
        dest: /tmp/install_ohmyzsh.sh
        mode: 'a+x'

    - name: Run Oh My Zsh installation script as user
      command: /tmp/install_ohmyzsh.sh --unattended && source ~/.zshrc
      become: true
      become_user: "{{ user }}"
      environment:
        ZSH: "/home/{{ user }}/.oh-my-zsh"
