- name: Install and configure Zsh and Oh My Zsh
  hosts: localhost
  become: yes
  tasks:
    - name: Install Zsh
      apt:
        name: zsh
        state: present

    - name: Set Zsh as the default shell for the ansible_user
      user:
        name: ansible_user
        shell: /bin/zsh

    - name: Install Oh My Zsh
      become: no
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      args:
        creates: /home/ansible_user/.oh-my-zsh

    - name: Change default shell to Zsh
      shell: |
        chsh -s $(which zsh) ansible_user
      args:
        executable: /bin/bash

    - name: Ensure .zshrc is present
      copy:
        src: /home/ansible_user/.oh-my-zsh/templates/zshrc.zsh-template
        dest: /home/ansible_user/.zshrc
        remote_src: yes
        owner: ansible_user
        group: ansible_user
