- name: Install and configure Zsh and Oh My Zsh
  hosts: localhost
  become: yes

  vars:
    user: stijn
    zsh_shell: /bin/zsh
    oh_my_zsh_install_script: https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh
  tasks:
    - name: Install Zsh
      apt:
        name: zsh
        state: present

    - name: Set Zsh as the default shell for the user
      user:
        name: "{{ user }}"
        shell: "{{ zsh_shell }}"

    - name: Install Oh My Zsh
      become: no
      shell: |
        sh -c "$(curl -fsSL {{ oh_my_zsh_install_script }})" "" --unattended
      args:
        creates: "/home/{{ user }}/.oh-my-zsh"

    - name: Change default shell to Zsh
      shell: |
        chsh -s {{ zsh_shell }} {{ my_user }}
      args:
        executable: /bin/bash

    - name: Ensure .zshrc is present
      copy:
        src: "/home/{{ user }}/.oh-my-zsh/templates/zshrc.zsh-template"
        dest: "/home/{{ user }}/.zshrc"
        remote_src: yes
        owner: "{{ user }}"
        group: "{{ user }}"
